blank_issues_enabled: false
contact_links:
  - name: LinkedIn (preferred contact)
    url: https://www.linkedin.com/in/komiljon-karimov-secops
    about: Message me directly for private feedback or permissions.
