name: Portfolio feedback
description: Suggest a correction or improvement to a lab or README
title: "[Feedback] <area>: <short summary>"
labels: ["feedback"]
body:
  - type: input
    id: path
    attributes:
      label: File or folder path
      placeholder: "e.g., 03_Network_Security/Lab01_Asset_Discovery/README.md"
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What’s the issue?
      placeholder: "Describe the inaccuracy/risk or improvement opportunity."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed fix (one paragraph)
  - type: dropdown
    id: risk
    attributes:
      label: Risk level
      options: ["info", "low", "medium", "high"]
      default: 0
  - type: input
    id: refs
    attributes:
      label: References / evidence (optional)
      placeholder: "Links to docs, standards, or sources"
