Vagrant.configure("2") do |config|
  config.vm.define "kali" do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = "kali"
    kali.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "dc10" do |dc|
    dc.vm.box = "gusztavvargadr/windows-10"
    dc.vm.hostname = "dc10"
    dc.vm.network "private_network", ip: "192.168.56.11"
    dc.vm.communicator = "winrm"
  end
end
